apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: dancers-town-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dancerstown.org
  dnsNames:
    - dancerstown.org
    - www.dancerstown.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - dancerstown.org
          - www.dancerstown.org
